# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CACBBP5DQkRuETJkXafAw9VX-7Xq97EO
"""

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import gradio as gr

# Load model
model = AutoModelForCausalLM.from_pretrained("model")
tokenizer = AutoTokenizer.from_pretrained("model")
tokenizer.pad_token = tokenizer.eos_token

# Chat function
def chat_llmind(user_input):
    prompt = f"User: {user_input}\nBot:"
    inputs = tokenizer(prompt, return_tensors="pt")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=80,
            pad_token_id=tokenizer.eos_token_id,
            do_sample=True,
            top_k=40,
            top_p=0.9,
            temperature=0.7,
            eos_token_id=tokenizer.eos_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "Bot:" in response:
        return response.split("Bot:")[-1].strip()
    return response.strip()

# Interface
iface = gr.Interface(
    fn=chat_llmind,
    inputs="text",
    outputs="text",
    title="LLMind - Aryan's Personal AI",
    description="Fine-tuned chatbot built by Aryan using DialoGPT."
)

if __name__ == "__main__":
    iface.launch()